import type { MessageGroup } from "../generic/schema/SyntaxDefinition.js";

export const CommandDefinitions: MessageGroup = {
    name: "Command",
    taggedUnionProperty: "messageKind",
    sharedProperties: [
        {
            name: "commandId",
            type: "CommandId",
            isList: false,
            isOptional: false,
            mayBeNull: false,
        },
        {
            name: "messageKind",
            type: "String",
            isList: false,
            isOptional: false,
            mayBeNull: false,
        },
        {
            name: "additionalInfos",
            type: "AdditionalInfo",
            isList: true,
            isOptional: false,
            mayBeNull: false,
        },
    ],
    messages: [
        {
            name: "AddPartition",
            properties: [
                {
                    name: "newPartition",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "split",
                    type: "Boolean",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "DeletePartition",
            properties: [
                {
                    name: "deletedPartition",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChangeClassifier",
            properties: [
                {
                    name: "newClassifier",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "node",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AddProperty",
            properties: [
                {
                    name: "node",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "property",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newValue",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChangeProperty",
            properties: [
                {
                    name: "node",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "property",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newValue",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "DeleteProperty",
            properties: [
                {
                    name: "node",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "property",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AddChild",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newChild",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "split",
                    type: "Boolean",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "DeleteChild",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReplaceChild",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newChild",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "split",
                    type: "Boolean",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveChildFromOtherContainment",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveChildFromOtherContainmentInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveChildInSameContainment",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveAndReplaceChildFromOtherContainment",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveAndReplaceChildFromOtherContainmentInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveAndReplaceChildInSameContainment",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "indexOffset",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AddAnnotation",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newAnnotation",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "split",
                    type: "Boolean",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "DeleteAnnotation",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReplaceAnnotation",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newAnnotation",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "split",
                    type: "Boolean",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveAnnotationFromOtherParent",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveAnnotationInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveAndReplaceAnnotationFromOtherParent",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "MoveAndReplaceAnnotationInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "indexOffset",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AddReference",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newReference",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: true,
                },
                {
                    name: "newResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: true,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "DeleteReference",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedReference",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: true,
                },
                {
                    name: "deletedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: true,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChangeReference",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldReference",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: true,
                },
                {
                    name: "oldResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: true,
                },
                {
                    name: "newReference",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: true,
                },
                {
                    name: "newResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: true,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ContinuedCommand",
            properties: [
                {
                    name: "chunk",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "continuedChunkCompleted",
                    type: "Boolean",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "continuedChunkSequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "CompositeCommand",
            properties: [
                {
                    name: "parts",
                    type: "Command",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "commandId",
                    type: "CommandId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "additionalInfos",
                    type: "AdditionalInfo",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
    ],
};
