import { MessageGroup } from "../generic/schema/SyntaxDefinition.js";

export const EventDefinitions: MessageGroup = {
    name: "Event",
    taggedUnionProperty: "messageKind",
    sharedProperties: [
        {
            name: "sequenceNumber",
            type: "Number",
            isList: false,
            isOptional: false,
            mayBeNull: false,
        },
        {
            name: "originCommands",
            type: "CommandSource",
            isList: true,
            isOptional: false,
            mayBeNull: false,
        },
        {
            name: "messageKind",
            type: "String",
            isList: false,
            isOptional: false,
            mayBeNull: false,
        },
        {
            name: "protocolMessages",
            type: "ProtocolMessage",
            isList: true,
            isOptional: false,
            mayBeNull: false,
        },
    ],
    messages: [
        {
            name: "ClassifierChanged",
            properties: [
                {
                    name: "node",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldClassifier",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newClassifier",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "PartitionAdded",
            properties: [
                {
                    name: "newPartition",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "PartitionDeleted",
            properties: [
                {
                    name: "deletedPartition",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "PropertyAdded",
            properties: [
                {
                    name: "node",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "property",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newValue",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "PropertyDeleted",
            properties: [
                {
                    name: "node",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "property",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldValue",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "PropertyChanged",
            properties: [
                {
                    name: "node",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "property",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newValue",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldValue",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildAdded",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newChild",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildDeleted",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildReplaced",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newChild",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildMovedFromOtherContainment",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildMovedFromOtherContainmentInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildMovedInSameContainment",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildMovedAndReplacedFromOtherContainment",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildMovedAndReplacedFromOtherContainmentInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldContainment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ChildMovedAndReplacedInSameContainment",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "containment",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedChild",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AnnotationAdded",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newAnnotation",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AnnotationDeleted",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedAnnotation",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AnnotationReplaced",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newAnnotation",
                    type: "LionWebDeltaJsonChunk",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AnnotationMovedFromOtherParent",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AnnotationMovedInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AnnotationMovedAndReplacedFromOtherParent",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "AnnotationMovedAndReplacedInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedAnnotation",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedDescendants",
                    type: "LionWebId",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceAdded",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "newResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceDeleted",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "deletedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceChanged",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "newResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "oldTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "oldResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "EntryMovedFromOtherReference",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newReference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldReference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "movedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "EntryMovedFromOtherReferenceInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newReference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldReference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "movedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "EntryMovedInSameReference",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "movedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "EntryMovedAndReplacedFromOtherReference",
            properties: [
                {
                    name: "newParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newReference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldParent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldReference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "movedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "replacedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "replacedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "EntryMovedAndReplacedFromOtherReferenceInSameParent",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newReference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldReference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "movedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "replacedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "replacedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "EntryMovedAndReplacedInSameReference",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "oldIndex",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "movedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "movedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "replacedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "replacedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceResolveInfoAdded",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "target",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceResolveInfoDeleted",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "target",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceResolveInfoChanged",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "target",
                    type: "LionWebId",
                    isList: false,
                    isOptional: true,
                    mayBeNull: false,
                },
                {
                    name: "oldResolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceTargetAdded",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "resolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceTargetDeleted",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "resolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "deletedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ReferenceTargetChanged",
            properties: [
                {
                    name: "parent",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "index",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "reference",
                    type: "LionWebJsonMetaPointer",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "resolveInfo",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "newTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "replacedTarget",
                    type: "LionWebId",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "CompositeEvent",
            properties: [
                {
                    name: "parts",
                    type: "Event",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "NoOp",
            properties: [
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
        {
            name: "ErrorEvent",
            properties: [
                {
                    name: "errorCode",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "message",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "sequenceNumber",
                    type: "Number",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "originCommands",
                    type: "CommandSource",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "messageKind",
                    type: "String",
                    isList: false,
                    isOptional: false,
                    mayBeNull: false,
                },
                {
                    name: "protocolMessages",
                    type: "ProtocolMessage",
                    isList: true,
                    isOptional: false,
                    mayBeNull: false,
                },
            ],
        },
    ],
};
