@startuml
hide empty members

' qualified name: "library"


class Book {
  title: String
  pages: Integer
}

class GuideBookWriter extends Writer {
  countries: String
}

class Library {
  name: String
}

class SpecialistBookWriter extends Writer {
  subject: String
}

class Writer {
  name: String
}



' relations:

Book "*" -- "*" Writer: author

Library "1" o-- "*" Book: books



legend
  <#LightGray,#LightGray>| <#Orange>Programmatic |
end legend
@enduml
