@startuml
hide empty members

' qualified name: "LIonCore"


class Concept extends FeaturesContainer {
  abstract: boolean
}

class ConceptInterface extends FeaturesContainer

class Containment extends Link

abstract class DataType extends MetamodelElement

class Enumeration extends DataType implements NamespaceProvider

class EnumerationLiteral extends NamespacedEntity

abstract class Feature extends NamespacedEntity {
  optional: boolean
  #Orange derived: boolean
}

abstract class FeaturesContainer extends MetamodelElement implements NamespaceProvider {
  allFeatures(): List<Feature>
}

' primitive type: "JSON"

abstract class Link extends Feature {
  multiple: boolean
}

class Metamodel implements NamespaceProvider {
  qualifiedName: String
}

abstract class MetamodelElement extends NamespacedEntity

interface NamespaceProvider {
  namespaceQualifier(): String
}

abstract class NamespacedEntity {
  simpleName: String
  qualifiedName(): String
}

class PrimitiveType extends DataType

class Property extends Feature

class Reference extends Link

' primitive type: "String"

' primitive type: "boolean"

' primitive type: "int"



' relations:

Concept "*" -- "0..1" Concept: extends
Concept "*" -- "*" ConceptInterface: implements

ConceptInterface "*" -- "*" ConceptInterface: extends

Enumeration "1" o-- "*" EnumerationLiteral: literals

FeaturesContainer "1" o-- "*" Feature: features

Link "*" -- "1" FeaturesContainer: type

Metamodel "1" o-- "*" MetamodelElement: elements
Metamodel "*" -- "*" Metamodel: dependsOn

NamespacedEntity "*" -- "1" NamespaceProvider: container

Property "*" -- "1" DataType: type


legend
  <#LightGray,#LightGray>| <#Orange>Disputed |
end legend
@enduml
