@startuml
hide empty members

' qualified name: "LIonCore.M3"


class Concept extends FeaturesContainer {
  abstract: Boolean
}

class ConceptInterface extends FeaturesContainer

class Containment extends Link

abstract class DataType extends MetamodelElement

class Enumeration extends DataType implements NamespaceProvider

class EnumerationLiteral extends NamespacedEntity

abstract class Feature extends NamespacedEntity {
  optional: Boolean
  #Orange derived: Boolean
}

abstract class FeaturesContainer extends MetamodelElement implements NamespaceProvider {
  allFeatures(): List<Feature>
}

abstract class Link extends Feature {
  multiple: Boolean
}

class Metamodel implements NamespaceProvider {
  qualifiedName: String
}

abstract class MetamodelElement extends NamespacedEntity

interface NamespaceProvider {
  namespaceQualifier(): String
}

abstract class NamespacedEntity {
  simpleName: String
  qualifiedName(): String
}

class PrimitiveType extends DataType

class Property extends Feature {
  programmatic: Boolean
}

class Reference extends Link



' relations:

Concept "*" -- "0..1" Concept: extends
Concept "*" -- "*" ConceptInterface: implements
ConceptInterface "*" -- "*" ConceptInterface: extends


Enumeration "1" o-- "*" EnumerationLiteral: literals


FeaturesContainer "1" o-- "*" Feature: features
Link "*" -- "1" FeaturesContainer: type
Metamodel "1" o-- "*" MetamodelElement: elements
Metamodel "*" -- "*" Metamodel: dependsOn




Property "*" -- "1" DataType: type


legend
  <#LightGray,#LightGray>| <#Orange>Programmatic |
end legend
@enduml
