@startuml
hide empty members

' qualified name: "LIonCore.stdlib"


' primitive type: "Boolean"

' primitive type: "Integer"

' primitive type: "JSON"

' primitive type: "String"



' relations:






legend
  <#LightGray,#LightGray>| <#Orange>Disputed |
end legend
@enduml
